version: "3.8"

services:
  lift-and-eat-frontend:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "3009" # Expose port only for the first instance
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lift-and-eat-frontend.rule=Host(`lift-and-eat.nibrasoft.com`)"
      - "traefik.http.routers.lift-and-eat-frontend.entrypoints=websecure"
      - "traefik.http.routers.lift-and-eat-frontend.tls=true"
      - "traefik.http.routers.lift-and-eat-frontend.tls.certresolver=le"
      - "traefik.http.routers.lift-and-eat-frontend.tls.domains[0].main=lift-and-eat.nibrasoft.com"
      - "traefik.http.middlewares.lift-and-eat-frontend-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.lift-and-eat-frontend.middlewares=lift-and-eat-frontend-redirect"
    volumes:
      - "~/shared_vps/traefik/certs:/letsencrypt" # Ensure correct path and permissions for volumes
    networks:
      - traefikNetwork
      - liftAndEatNet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3009/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  traefikNetwork:
    external: true
  liftAndEatNetNet:
    driver: bridge
    internal: true
