version: "3.8"

services:
  lift-and-eat-frontend:
    build:
      context: .
      dockerfile: prod.Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lift-and-eat-frontend.rule=Host(`lift-and-eat.nibrasoft.com`)"
      - "traefik.http.routers.lift-and-eat-frontend.entrypoints=websecure"
      - "traefik.http.routers.lift-and-eat-frontend.tls=true"
      - "traefik.http.routers.lift-and-eat-frontend.tls.certresolver=le"
      - "traefik.http.services.lift-and-eat-frontend.loadbalancer.server.port=3009"

    volumes:
      - "~/shared_vps/traefik/certs:/letsencrypt" # Ensure correct path and permissions for volumes
    networks:
      - traefikNetwork
      - lift-and-eatNet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  traefikNetwork:
    external: true
  lift-and-eatNet:
    driver: bridge
    internal: true
