version: "3.8"

services:
  lift-and-eat-frontend:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - 3009:3009
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lift-and-eat-frontend.rule=Host(`lift-and-eat.nibrasoft.com`)"
      - "traefik.http.routers.lift-and-eat-frontend.entrypoints=websecure"
      - "traefik.http.routers.lift-and-eat-frontend.tls=true"
      - "traefik.http.routers.lift-and-eat-frontend.tls.certresolver=le"
      - "traefik.http.routers.lift-and-eat-frontend.tls.domains[0].main=lift-and-eat.nibrasoft.com"
      - "traefik.http.middlewares.lift-and-eat-frontend-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.lift-and-eat-frontend.middlewares=lift-and-eat-frontend-redirect"

    networks:
      - traefikNetwork
      - lift-and-eatNet
    volumes:
      - "~/shared_vps/traefik/certs:/letsencrypt"
networks:
  traefikNetwork:
    external: true
  lift-and-eatNet:
    internal: true
